[Feat💡] 장소 추가 내의 검색 기능
AI-iLearning/AI-Learning pull request #111
Opened 2024-09-20 17:08 UTC by katekim512

## #️⃣연관된 이슈

close #106 

## 💡 핵심적으로 구현된 사항
- 장소 추가 검색 기능
- useAllPlace 불러와서 검색 시 사용

https://github.com/user-attachments/assets/72849bff-892c-435d-8353-e0308a75f5bf

## 🚀 로직 설명 및 코드 설명

 - /hooks/useAllPlace.ts 이용 -> 전체 목록 불러와서 사용
<img width="192" alt="image" src="https://github.com/user-attachments/assets/be84801f-8cd6-4992-8998-b6572e3b2753">

- data (locationData) -> cityMapper 못 찾아서 하나 만들어서 했습니다! 같은 코드면 지우고 cityMapper로 통일해도 좋을 것 같습니다
- SearchBar.tsx로 검색 기능 관련 부분 모두 따로 관리

- 향후 dummydata 관련 부분 지우면서 dummy.png도 함께 삭제
   - 서버 안 켜져있는 경우가 많아서 그냥 하나 넣어놨습니다

## ⚠️ 마주쳤던 문제 및 해결 방법
없음

## ➕ 그 외에 추가적으로 구현된 사항
없음

## 🤔 테스트,검증 && 고민 사항
- GPS 관련 부분도 따로 분리해서 사용하면 좋을 것 같아서 Refactor 고려 대상
- 검색을 하는 순간 추천장소 내에서의 검색이 아니라 전체에서의 검색이라 "00월 00일 추천장소" 말고 다른 워딩으로 바꿀지 고민해보면 좋을 것 같아요

### 📌 PR Comment 작성 시 Prefix for Reviewers

2024-09-21 10:37 UTC, jiheunkim requested changes
리뷰 남긴 거 참고해서 다시 올려주고, 검색 장소에 해당하는 것이 없는 경우 피그마 디자인 참고해서 그렇게 뜨도록 변경해주세용

로딩중도 아래와 같은 게 가운데에 뜨도록 수정해주세요!
![image](https://github.com/user-attachments/assets/3cea8e1d-2a05-4b26-b3ce-85fb4cc1ed82)

2024-09-21 10:37 UTC, jiheunkim commented on frontend/src/pages/CalendarPage/components/AddPlace.tsx
gps 요청 보냈을 때 반환값이 0이면 인근 근처에 아무 장소 없다는 걸 알려주기! 지금은 계속 로딩중 상태가 유지됨!

2024-09-21 10:37 UTC, jiheunkim commented on frontend/src/pages/CalendarPage/components/AddPlace.tsx
지금 코드 짠 거 돌려보면 검색 시 무한으로 코드가 돌아가고 있음! 서비스가 돌아가는데 엄청 치명적!!

SearchBar.tsx:43  Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.

이 경고가 뜨게 하면 안됨!

검색할 때 데이터 자체도 방대하게 들어오면 문제가 돼서, RecommendDetail.tsx 파일 보면 반환되는 총 장소 값을 한 번에 띄워주는 게 아니라 20개씩 끊어서 보여주게 짜뒀음. 스크롤의 끝 부분에 도달하면 추가로 20개 더 불러와서 보여주는 방식으로 AddPlace.tsx도 변경해주기

**요약하자면 f12로 돌려봤을 때 무한으로 돌아가고 위와 같은 경고가 뜨면 안된다는 것!**

2024-09-21 10:37 UTC, jiheunkim commented on frontend/src/pages/CalendarPage/components/data/locationData.tsx
이거 파일 구조 components 안에 data 만들어서 넣어뒀는데, components랑 같은 위치에 data 만들기!
그니까 data 한 단계 상위 위치로 빼기!!

2024-09-21 10:37 UTC, jiheunkim commented on frontend/src/pages/CalendarPage/styles/dummy.png
dummy.png 사용하지 말고, 필요시 public > img > default_pic.png 사용하세여! 이 부분은 삭제하고 AddPlace.tsx에 있는 더미도 다 삭제해서 올려주세욤

2024-09-21 10:39 UTC, jiheunkim commented
> ## #️⃣연관된 이슈
> close #106
> 
> ## 💡 핵심적으로 구현된 사항
> * 장소 추가 검색 기능
> * useAllPlace 불러와서 검색 시 사용
> 
>  2024-09-21.1.53.37.mov 
> ## 🚀 로직 설명 및 코드 설명
> * /hooks/useAllPlace.ts 이용 -> 전체 목록 불러와서 사용
> 
> <img alt="image" width="192" src="https://private-user-images.githubusercontent.com/127101670/369489344-be84801f-8cd6-4992-8998-b6572e3b2753.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5MTUzNTAsIm5iZiI6MTcyNjkxNTA1MCwicGF0aCI6Ii8xMjcxMDE2NzAvMzY5NDg5MzQ0LWJlODQ4MDFmLThjZDYtNDk5Mi04OTk4LWI2NTcyZTNiMjc1My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMVQxMDM3MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02Y2MwY2Y2Y2NmZWZhNTcxYzk0OTM1N2VlMjljMGM3MGE3ZDM0MjE1YmQ4NGY4ZTg0M2M4ZmJmM2ZlNWM5NDU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.rk6Yo_7ymLwU4avfcvf4-uDlZK4QcJwxDV7W0kcX9uU">
> * CityMapper 사용해서 시군구 코드와 지역 명칭 매칭
> * SearchBar.tsx로 검색 기능 관련 부분 모두 따로 관리
> * 향후 dummydata 관련 부분 지우면서 dummy.png도 함께 삭제
>   
>   * 서버 안 켜져있는 경우가 많아서 그냥 하나 넣어놨습니다
> 
> ## ⚠️ 마주쳤던 문제 및 해결 방법
> 없음
> 
> ## ➕ 그 외에 추가적으로 구현된 사항
> 없음
> 
> ## 🤔 테스트,검증 && 고민 사항
> * GPS 관련 부분도 따로 분리해서 사용하면 좋을 것 같아서 Refactor 고려 대상
> * 검색을 하는 순간 추천장소 내에서의 검색이 아니라 전체에서의 검색이라 "00월 00일 추천장소" 말고 다른 워딩으로 바꿀지 고민해보면 좋을 것 같아요
> 
> ### 📌 PR Comment 작성 시 Prefix for Reviewers

검색을 하는 순간 추천장소 내에서의 검색이 아니라 전체에서의 검색이라 "00월 00일 추천장소" 말고 다른 워딩으로 바꿀지 고민해보면 좋을 것 같아요 -> 이거 검색할 시 그냥 그 라인이 아예 안보이도록 해도 될 거 같고, 전자로 했을 때 좀 그러면 기존 유지??

2024-09-21 17:27 UTC, katekim512 commented on frontend/src/pages/CalendarPage/components/data/locationData.tsx
✨ 이거는 CityMapper 사용해서 삭제하겠습니다! 안써요!

2024-09-21 17:34 UTC, katekim512 commented on frontend/src/pages/CalendarPage/components/AddPlace.tsx
✨ 검색어 입력할 때만 요청하도록 수정하였습니다!

2024-09-21 17:43 UTC, katekim512 commented on frontend/src/pages/CalendarPage/styles/dummy.png
✨ 수정했습니다!

2024-09-21 23:43 UTC, jiheunkim requested changes
리뷰 남긴 거 토대로 수정 부탁해용

2024-09-21 23:43 UTC, jiheunkim commented on frontend/src/pages/CalendarPage/components/AddPlace.tsx
gps 요청 보냈을 때 반환값이 0이면 인근 근처에 아무 장소 없다는 걸 알려주기! 지금은 계속 로딩중 상태가 유지됨!
-> 이 부분은 안되는 것 같은데..! 무한 로딩이 되는 거 같음

2024-09-21 23:43 UTC, jiheunkim commented on frontend/src/pages/CalendarPage/components/AddPlace.tsx
![image](https://github.com/user-attachments/assets/445dc0c2-af48-4ad0-b7e7-c759317c39de)

앱 화면에서는 맞는데 웹 화면에서 지금 이렇게 떠서 이건 맞춰주는 게 좋을 거 같음!

2024-09-21 23:43 UTC, jiheunkim commented on frontend/src/pages/CalendarPage/components/AddPlace.tsx
검색 전반적으로 잘 고쳤는데,

기존은 areacode, sigungucode를 받아서 한글로 변환하는 작업이었다면, 이건 반대로 해주는 게 필요함!

그래서

``` ts
  const cityByAreaCode: { [key: number]: string } = {
    1: '서울',
    2: '인천',
    3: '대전',
    4: '대구',
    5: '광주',
    6: '부산',
    7: '울산',
    8: '세종',
    39: '제주',
  }
```

여기서 언급되는 곳은 sigungucode 내 이름은 포함하지 않고 있어서 이 부분을 고려해서 검색 반영해줘야함!
예시로 지금 검색에서 '강남'을 쳤을 때 바람직한 결과는 sigungucode 중 강남구인 것을 포함한 결과값을 반환해줘야함! 그렇지만 CityMapper.ts에서 얻을 수 있는 정보는 '서울'인 areacode 관계 뿐이여서 이런 걸 고려해서 수정해줘야함!!

2024-09-22 04:13 UTC, katekim512 commented
> 리뷰 남긴 거 토대로 수정 부탁해용

(답변이 안 달려서 🥹 여기다가 따로 작성해요!)

✨ 로딩 페이지 수정 완
✨ 해당 장소 없음 페이지 구축 완
✨ 무한 로딩 해결 완
✨ 결과 / 로딩 / 해당 없음 페이지 뜨는 로직 수정 완
 -  검색창 입력값이 있으면 -> 전체에서 찾아서 띄워주기 -> 없으면 해당 장소 없음
 - 검색창 입력값이 없으면 -> 추천 장소나 GPS 기반 추천 장소 띄워주기
 
✨ 검색어 관련 궁금한 점 -> 강남구가 없는데 내가 추가로 딕셔너리를 더 만들어야하는 부분이 있는건가?

2024-09-22 18:21 UTC, jiheunkim approved these changes
확인완료!
내 위치 기반 장소 관련 이슈는 추후 생각...

2024-09-22 18:21 UTC, merged