[Feat💡] EachLevel Page 구축
AI-iLearning/AI-Learning pull request #112
Opened 2024-09-21 04:30 UTC by katekim512

## #️⃣연관된 이슈

close #96

## 💡 핵심적으로 구현된 사항
- 레벨별목록 컴포넌트 UI (피그마 기반)
- 레벨별 목록 반환
- 방문장소 여부 체크
- Mylevel -> url에 Level 정보 가지고 넘기기
- 해당 Level 정보 타이틀에 띄워주기

https://github.com/user-attachments/assets/df444025-f56c-45be-b194-8d93c408ce18

## 🚀 로직 설명 및 코드 설명

 - api/profile/postLevel.ts 구축
<img width="238" alt="image" src="https://github.com/user-attachments/assets/fa561ad9-7dc4-432c-b10a-1ba7b913ba56">

- ProfilePage 밑에  Component로 추가
- LevelItem 만들어서 EachLevel (목록) 에서 사용

- 향후 dummydata 관련 부분 지우면서 dummy.png도 함께 삭제

## ⚠️ 마주쳤던 문제 및 해결 방법
없음

## ➕ 그 외에 추가적으로 구현된 사항
없음

## 🤔 테스트,검증 && 고민 사항
없음

### 📌 PR Comment 작성 시 Prefix for Reviewers

2024-09-21 10:52 UTC, jiheunkim requested changes
수정하고 다시 올려주세용

2024-09-21 10:52 UTC, jiheunkim commented on frontend/src/api/profile/postLevel.ts
요청 바디가 level 하나밖에 없어서 그냥 바로 level로 하는 게 더 깔끔할 거 같아

``` ts
import { AxiosResponse } from 'axios'

import { aiLearningAxios } from '../axiosInstance'

interface LevelResponse {
  contentid: number
  contenttypeid: number
  areacode: number
  sigungucode: number
  place: string
  firstimage: string
  isVisited: boolean
}

export const postLevel = async (
  token: string,
  level: string,
): Promise<AxiosResponse<LevelResponse> | null> => {
  const response = await aiLearningAxios.post<LevelResponse>(
    'profile/level',
    { level },
    {
      headers: { Authorization: `Bearer ${token}` },
    },
  )
  return response
}

```

2024-09-21 10:52 UTC, jiheunkim commented on frontend/src/pages/ProfilePage/styles/LevelItem.style.tsx
방문 완료의 경우

![image](https://github.com/user-attachments/assets/02bf928b-8626-42f4-998f-4cb04d983e6f)

이렇게 이미지 위치에 체크 표시 되도록..!

2024-09-21 10:52 UTC, jiheunkim commented on frontend/src/pages/ProfilePage/styles/EachLevel.style.tsx
아직 방문하지 않음 여기 아래 bottom line 색상 메인 색상으로 맞춰줘!
![image](https://github.com/user-attachments/assets/2dabaf47-0d1c-4a30-99e9-1c855115a436)
![image](https://github.com/user-attachments/assets/27d8894f-a228-4e4f-a66e-cdefdd06ac79)

2024-09-21 10:52 UTC, jiheunkim commented on frontend/src/pages/ProfilePage/styles/dummy.png
이 이미지는 삭제하고 필요시 public > img > default_pic.png 사용하기

2024-09-21 10:52 UTC, jiheunkim commented on frontend/src/pages/ProfilePage/styles/LevelItem.style.tsx
그리고 스크롤 그냥 전체 페이지가 다 내려갈 수 있게 변경해주면 좋을 거 같아!! 맨 위부터!

2024-09-22 04:35 UTC, katekim512 commented on frontend/src/api/profile/postLevel.ts
✨ 수정 완

2024-09-22 04:50 UTC, katekim512 commented on frontend/src/pages/ProfilePage/styles/LevelItem.style.tsx
✨수정 완

2024-09-22 04:51 UTC, katekim512 commented on frontend/src/pages/ProfilePage/styles/EachLevel.style.tsx
✨ 수정 완

2024-09-22 04:52 UTC, katekim512 commented on frontend/src/pages/ProfilePage/styles/dummy.png
✨수정 완

2024-09-22 06:33 UTC, jiheunkim approved these changes
확인완료!

2024-09-22 06:33 UTC, merged