[Feat💡] AI 일정(3) Delete 기능 추가
AI-iLearning/AI-Learning pull request #119
Opened 2024-09-23 17:37 UTC by katekim512

## #️⃣연관된 이슈

close #96

## 💡 핵심적으로 구현된 사항
- backButton 위치 조정 (AISchedule1이랑 2페이지랑 위치 동일하게)
- 왼쪽 슬라이드 시 삭제 기능 추가
- 가이드 연결 문구 달기

<table>
  <tr>
    <td>
<video src="https://github.com/user-attachments/assets/727280c5-8060-48b1-851d-2f6b79b1be52" controls width="500"></video>
    </td>
    <td>
      <img width="295" alt="스크린샷 2024-09-24 오전 2 31 01" src="https://github.com/user-attachments/assets/b2ec4c14-b40a-4ae9-97a9-7763204d5b29">
    </td>
  </tr>
</table>

## 🚀 로직 설명 및 코드 설명

 - isSwipe를 통해서 왼쪽으로 swipe 된 상태인지 확인 -> swipe 되어있으면 삭제 버튼 나타남
 - 삭제 버튼 누를 시 swipe 안된 원래 상태로 복귀
 - 백엔드에 전달되는 시점은 "확인" 버튼 눌렀을 때

## ⚠️ 마주쳤던 문제 및 해결 방법
- 아이콘 filled 라서 그런지 색상(그라데이션)이 안 먹어서 임시 방편으로 다른 아이콘 삽입

## ➕ 그 외에 추가적으로 구현된 사항
없음

## 🤔 테스트,검증 && 고민 사항
없음

### 📌 PR Comment 작성 시 Prefix for Reviewers

2024-09-24 13:07 UTC, jiheunkim requested changes
리뷰 체크해주세용

2024-09-24 13:07 UTC, jiheunkim commented on frontend/src/pages/AISchedule3Page/AISchedule3.tsx
참고로 적어두는데 iconify 일일이 다 npm install 할 필요없고, 여기서 받은 @iconify-icons/fluent의 경우

``` tsx
<Icon
  icon='fluent:people-chat-16-filled'
  width='24'
  height='24'
/>
```

이런 식으로 표현하면 아이콘 다 뜹니당

"@iconify/react": "^5.0.2", <- 이거 하나만 설치하면 된다는 말!

2024-09-24 13:07 UTC, jiheunkim commented on frontend/src/pages/AISchedule3Page/AISchedule3.tsx
삭제 기능 잘 되는 거 확인했습니다 더미데이터는 제거해주세용

2024-09-24 13:07 UTC, jiheunkim commented on frontend/src/pages/AISchedule3Page/AISchedule3.tsx
svg 말고 Icon이랑 글자 넣고 상위 div에 그라데이션 color 입혔을 때 안됐던 건가요??!

2024-09-24 13:08 UTC, jiheunkim commented
AI일정(1) 페이지 `강원도권` 추가도 여기서 같이 넣어주면 좋을 것 같음!!

2024-09-26 07:28 UTC, katekim512 commented on frontend/src/pages/AISchedule3Page/AISchedule3.tsx
> 참고로 적어두는데 iconify 일일이 다 npm install 할 필요없고, 여기서 받은 @iconify-icons/fluent의 경우
> 
> ```tsx
> <Icon
>   icon='fluent:people-chat-16-filled'
>   width='24'
>   height='24'
> />
> ```
> 
> 이런 식으로 표현하면 아이콘 다 뜹니당
> 
> "@iconify/react": "^5.0.2", <- 이거 하나만 설치하면 된다는 말!

✨ 해당 방식으로 반환 완료

2024-09-26 07:32 UTC, katekim512 commented on frontend/src/pages/AISchedule3Page/AISchedule3.tsx
> svg 말고 Icon이랑 글자 넣고 상위 div에 그라데이션 color 입혔을 때 안됐던 건가요??!

```
export const GuideRequestButton = styled.button`
  padding: 0 0 0 5px; /* top, right, bottom, left */
  margin-top: 0px;
  background: transparent;
  border: none;
  cursor: pointer;
  font-size: 14px;
  display: flex;
  align-items: center;
  position: relative;
  z-index: 0;

  // 텍스트에만 그라데이션 적용
  background-image: linear-gradient(to right, #00c6ff, #0072ff);
  -webkit-background-clip: text;
  background-clip: text;
  color: #0072ff;

  // 밑줄 제거
  text-decoration: none;

  &:hover {
    // 호버 시 스타일 변경이 필요하다면 여기에 추가
  }

  // 포커스 시 기본 아웃라인 제거
  &:focus {
    outline: none;
  }
`
```

- 이게 상위 div인데 
- 이 div 안에 ( Icon, 글씨) 이렇게 들어갑니당
-  그라데이션을 하려면 text color을 transparent로 하고 위에 색을 얹어야하는 방식으로 해야하는데 이 transparent 하면서 icon이 같이 투명이 되면서 아예 안 나타나는 것 처럼 뜹니다..! 다른 방법을 아직 못찾았어요..! 그라데이션 말고 다른 색상은 모두 가능합니다
    - 일단 파란색으로 설정해놓았습니다!

2024-09-26 07:35 UTC, katekim512 commented
> AI일정(1) 페이지 `강원도권` 추가도 여기서 같이 넣어주면 좋을 것 같음!!

<img width="294" alt="image" src="https://github.com/user-attachments/assets/2a16d472-52b6-4a65-adec-b3d3ea1ee1d9">
<br/>

- 추가했습니다!

2024-09-26 13:38 UTC, jiheunkim commented on frontend/src/pages/AISchedule3Page/AISchedule3.tsx
일단 확인완!

2024-09-26 13:40 UTC, jiheunkim approved these changes
확인했습니다

2024-09-26 13:40 UTC, jiheunkim commented on frontend/package.json
이건 왜 깔리는거지? 의문이군..

2024-09-26 13:40 UTC, merged

2024-09-26 15:13 UTC, katekim512 commented on frontend/package.json
❓ 아이콘 관련인건가...??