[Feat 💡] CalenderInput(캘린더) - 날짜
AI-iLearning/AI-Learning pull request #39
Opened 2024-08-03 17:08 UTC by katekim512

## #️⃣연관된 이슈

#14 

## 💡 핵심적으로 구현된 사항
<p>
<img alt="image" src="https://github.com/user-attachments/assets/a7b6ae49-cd33-4933-8fa8-de87a091cb47" width="30%" />
<img alt="image" src="https://github.com/user-attachments/assets/a34db316-9f9b-4a9d-92ae-37533a1c3601" width="30%" />
<img alt="image" src="https://github.com/user-attachments/assets/95e9ddc9-1cbf-4e51-acd2-14c459a629fb" width="30%" />
</p>

- 시작일 설정
  - 시작일 버튼 눌러서 날짜 선택 화면에 들어가면 디폴트로 현재 날짜가 선택되어져 있도록 함
  -시작일 설정 가능 기간: 현재 날짜부터 180일 후까지
    -ex) 현재 날짜가 24/7/20일 경우 25/1/15까지 선택가능영역

- 종료일 설정 페이지
  - 종료일 버튼 눌러서 날짜 선택 화면에 들어가면 디폴트로 시작일+29일 뒤 날짜가 선택되어져 있도록 함
    - ex) 시작일이 7/20이면 종료일 선택 화면 들어가면 디폴트 날짜는 8/17일
  - 종료일 설정 가능 기간: 시작일+29일 후부터 365일 후까지
    - ex) 시작일이 24/9/17인 경우, 24/10/15 ~ 25/9/16까지 선택가능영역
 
- 현재 날짜 아래 작은 동그라미로 구분점 해주기

## 🚀 로직 설명 및 코드 설명
1. 캘린더 UI 제작
2. 날짜 선택 
3. ai-schedule-1과 연결
4. default 값-> 캘린더 선택에 반영
5. (시작일/종료일) 선택 가능한 범위 조건에 맞게 설정
6. 선택 가능한 날짜들 포함한 달력들 띄워주기
<br>
<img width="296" alt="image" src="https://github.com/user-attachments/assets/3f9f834c-f5e8-4098-ac1b-4eec6bedf166">
<br>

### 파일 구조 설명 => CalenderInput 폴더 (오타 이슈..)

- 아래에 style 폴더 따로
   - style 관련해서 코드 한페이지 -> CalenderInput,CalenderInput2,CalendarFrame,CalendarFrame2 모두 하나의 페이지 참조
- CalendarFrame 이 메인 Calendar만 구현해놓은 부분 (CalendarFrame - 시작일, CalendarFrame2 - 종료일)
        - 버튼 활성화 조건 때문에 분리해놓음
- CalendarInput - x 버튼 & 아래 버튼까지 포함한 전체 페이지 (CalendarInput - 시작일, CalendarInput2- 종료일)

## ⚠️ 마주쳤던 문제 및 해결 방법
- UI 제작 시 - 날짜들을 그냥 string 형식으로 보냈는데 -> 선택이 안되는 현상 발생
  - 해결 방법 :  다 버튼으로 바꿈 -> 날짜 하나하나가 다 버튼임 / 전체 가로 7등분해서 grid로 맞춤 (style)
- console에는 잘 찍히는데 zustand 등에 반영 안됨
  - 날짜 형식으로 다 "YYYY MM DD" 형식으로 맞추었음
  - 2024-08-03 이랑 2024-8-3 이랑 다르게 인식해서 생겼던 문제 다수 (차후 트러블 슈팅 시 염두해두기)
 - 페이지 처음 로드할 때 현재 설정되어있는 default 값이 색칠이 되어야하는데 안되는 현상 발생
   - setTimeout 을 이용해서 고쳐놓긴 했지만 -> 추후 좋은 해결 방안 있으면 바꾸면 좋을 것 같음 
- 활성화 버튼 관련 문제 - 당일 선택 불가 이슈
  - 기준점을 어제로 해서 해결하긴 했으나 근본적인 이유를 아직 못 찾았음  

## ➕ 그 외에 추가적으로 구현된 사항

없음

## 🤔 테스트,검증 && 고민 사항
- X 버튼이 잘 안눌림, 조금 위 부분을 눌러야 눌리는데 디자인적 문제가 있는 것 같음 -> 추후 개선해야함
-  시작일을 설정하고 적용 버튼을 누르면  종료일 부분이 자동계산되어 29일 뒤 날짜로 보이게 함 (아직 구현 X)
- 변경 시, 전에 저장되어있던 값부터 시작되어야하는데 -> 다시 현재 기준으로 돌아가고 있음 (고쳤는데 다시 또 이러네,,다음에 다시 해보겠습니다,,)

### 📌 PR Comment 작성 시 Prefix for Reviewers

2024-08-03 17:45 UTC, jiheunkim requested changes
실행했을 때 UI 깔끔하게 잘 나와요✨

리뷰 남긴 것 중에 리팩토링 필요한 영역 빼고 수정해서 다시 풀리퀘 보내주면 머지할게여

2024-08-03 17:45 UTC, jiheunkim commented on frontend/src/components/BackButton/BackButton.tsx
지금 AI일정(1) 화면에서는 날짜 선택 화면도 이동했다가 나오기 때문에 BackButton을 눌렀을 때, 캘린더 메인 화면으로 돌아가는 게 아니라 날짜 선택 화면으로 이동하기도 함.

CalenderInputPage 내 components 폴더 생성해서 BackButton.tsx 따로 하나 더 생성해서 해당 BackButton 사용하기!
해당 BackButton은 navigate('/calendar') 시켜주면 될 것

2024-08-03 17:45 UTC, jiheunkim commented on frontend/src/components/BackButton/styles/BackButton.style.tsx
주석 제거해줘도 될 거 같아용

2024-08-03 17:45 UTC, jiheunkim commented on frontend/src/pages/AISchedule1Page/styles/AISchedule1.style.tsx
- Button인 경우 color 다 지정해주기! 그래야 앱 상에서 글자색이 올바르게 나옴!

![image](https://github.com/user-attachments/assets/1d333474-a03f-45f1-a550-37b84085ae86)
- 스크롤 영역 다음 버튼 바로 위까지 되게 변경! 현재는 미세한 여백이 존재함

2024-08-03 17:45 UTC, jiheunkim commented on frontend/src/pages/CalenderInputPage/styles/CalendarFrame.style.tsx
- 해당 CloseButton는 전역 Component로 기능할 수 있어서, src > components 폴더 내 CloseButton 파일을 만들어 불러오는 방식으로 만들어줬음 좋겠음!!
- 기능은 BackButton과 일치하기 때문에 모양만 바꾸면 될 거 같음.
- icon의 경우 현재 너무 두께가 굵기 때문에, 다른 icon 찾아서 적용하면 좋을 거 같음! iconify에 괜찮은 거 있을 거 같음

```tsx
export const CloseButton = styled.button`
  background: none;
  border: none;
  font-size: 1.5rem;
  cursor: pointer;
  display: flex;
  align-items: center;
`
```

- CalendarFrame.style.tsx과 CalendarInput.style.tsx 파일 분리해서 만들어주면 좋을 거 같아여!

2024-08-03 17:45 UTC, jiheunkim commented on frontend/src/pages/CalenderInputPage/CalendarFrame.tsx
- 원하는 바는 CalendarFrame과 CalendarInput을 각 1개씩만 만들어서 전달되는 값만 바꿔서 동작하게 하면 좋겠음! 이건 일단 추후 refactoring으로 진행해도 될 거 같음~~
- 파일 구조를 현재 CalenderInputPage 안에 Frame과 Input 파일이 총 4개 있는데 CalenderInputPage 폴더 안에 components 폴더 생성 CalendarFrame.tsx 파일 정리해주기!
- CalenderInputPage 폴더 이름도 **CalendarInputPage**로 오타 수정해서 이름 바꿔주기!

2024-08-04 03:08 UTC, katekim512 commented on frontend/src/components/BackButton/BackButton.tsx
✨해결했습니당

2024-08-04 03:09 UTC, katekim512 commented on frontend/src/components/BackButton/styles/BackButton.style.tsx
✨해결했습니당

2024-08-04 03:20 UTC, katekim512 commented on frontend/src/pages/AISchedule1Page/styles/AISchedule1.style.tsx
<img width="381" alt="image" src="https://github.com/user-attachments/assets/71bc76a5-1b6e-4d3d-baf6-08679a06cf14">


<br>

- 요렇게 수정하였습니다✨

2024-08-04 03:21 UTC, katekim512 commented on frontend/src/pages/CalenderInputPage/CalendarFrame.tsx
✨해결했습니당

2024-08-04 05:50 UTC, katekim512 commented on frontend/src/pages/CalenderInputPage/styles/CalendarFrame.style.tsx
<img width="384" alt="image" src="https://github.com/user-attachments/assets/6d113a7a-7ab5-43a2-88c7-976566ec8f9e">

- 요걸로 바꿨습니다!✨

2024-08-04 06:37 UTC, jiheunkim requested changes

2024-08-04 06:37 UTC, jiheunkim commented on frontend/src/pages/CalendarInputPage/CalendarInput.tsx
L.CloseButton 말고 src > components 안에 CloseButton 폴더 생성해서 CloseButton.tsx 넣어주기

navigate(-1)로 이전으로 이동하게끔 해서 전역 컴포넌트로 사용할 수 있게끔!

2024-08-04 08:20 UTC, katekim512 commented on frontend/src/pages/CalendarInputPage/CalendarInput.tsx
✨해결했습니당

2024-08-04 08:59 UTC, jiheunkim approved these changes
굿굿🍀

2024-08-04 08:59 UTC, merged