[Feat💡] AI일정 수정 기능 - 드래그앤드롭
AI-iLearning/AI-Learning pull request #65
Opened 2024-08-10 11:36 UTC by katekim512

## #️⃣연관된 이슈

#46 

## 💡 핵심적으로 구현된 사항
<p>

https://github.com/user-attachments/assets/b1f67eb0-c299-4461-b511-6df6996a0b69

</p>

- 일정 수정 기능 -> 드래그 & 드롭
- 변경된 일정 백엔드에 전달

### 세부 사항
- 사용시 적절한 멘트와 함수 전달해주면 사용 가능

## 🚀 로직 설명 및 코드 설명
### 파일 구조 설명 
- Schedule 과 내부의 ScheduleItem으로 분리 -> 전부 Components 안에 있음

## ⚠️ 마주쳤던 문제 및 해결 방법
- `npm install react-dnd react-dnd-html5-backend`
  - 이 라이브러리가 컴퓨터 마우스에만 작동하는 문제가 있어서 -> 크롬 아이폰12 기준 작동이 안됨
- `npm install react-dnd-touch-backend`
- 이것도 함께 설치해서 실행해줌
- 현재 기기가 모바일인지 PC인지 구분하기 위해
  - `npm install react-device-detect` 이것도 써보려고 했지만
  - 작동이 잘 되지 않아서 (아직 이유를 모르겠음)
  - 아래 형태로 모바일 구분을 해 줌
```
const isMobile = () => {
    const ua = navigator.userAgent
    return (
      /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(
        ua,
      ) ||
      (navigator.maxTouchPoints && navigator.maxTouchPoints > 2)
    )
  }
```
 

## ➕ 그 외에 추가적으로 구현된 사항

없음

## 🤔 테스트,검증 && 고민 사항
- 현재 실행하면 임시 데이터로 들어감 -> 화면 확인을 위해
- 밑에 주석해놓은 부분 풀면 백엔드에서 데이터 받아와서 띄워주는 형태로 바뀜!

### 📌 PR Comment 작성 시 Prefix for Reviewers

2024-08-10 12:42 UTC, jiheunkim requested changes
리뷰 참고해서 다시 보내주세용

2024-08-10 12:42 UTC, jiheunkim commented on frontend/src/pages/AISchedule3Page/AISchedule3.tsx
드래그 작동 잘 되면 백엔드 api 주석 처리된 거 해제해서 해주세용! API 수정 테스트 해야해서 그 버전으로 배포에 붙이는 게 좋을 거 같아여

2024-08-10 12:42 UTC, jiheunkim commented on frontend/src/pages/AISchedule3Page/components/Schedule.tsx
![image](https://github.com/user-attachments/assets/8ddfc94e-d241-4338-bf0f-9d3147a40761)

- 이렇게 그 칸 전체 영역을 드래그 가능 영역으로 하지 말고 끝에 바를 눌러서 옮길 수 있게끔으로 수정 부탁!!
- 멘트도 수정을 원하는 일정을 ~ 이거 맞게 고쳐줘용!

2024-08-11 11:59 UTC, katekim512 commented on frontend/src/pages/AISchedule3Page/AISchedule3.tsx
✨그렇게 해놓았습니당

2024-08-11 12:00 UTC, katekim512 commented on frontend/src/pages/AISchedule3Page/components/Schedule.tsx
✨반영했습니다!

2024-08-11 15:23 UTC, jiheunkim approved these changes
굿굿😎

2024-08-11 15:24 UTC, merged