[Feat💡] 장소 추천(지도) + 장소 추천 세부페이지 구축
AI-iLearning/AI-Learning pull request #89
Opened 2024-09-14 10:02 UTC by katekim512

## #️⃣연관된 이슈

close #73 
close #84 

## 💡 핵심적으로 구현된 사항

      
<img width=45% alt="스크린샷 2024-09-14 오후 7 01 15" src="https://github.com/user-attachments/assets/25718990-e02d-472e-b1a8-998794c4783f">

<img width=45% alt="스크린샷 2024-09-12 오후 10 36 39" src="https://github.com/user-attachments/assets/c88cb502-ed14-4d0e-a1cd-1e3004ee660d">

- 장소 추천 (지도) - Recommend
  - 장소추천 UI (피그마 기반)
  - 각 지역 누르면 해당 지역 추천 장소 페이지(오른쪽) 으로 이동
  - 모두보기 클릭 시 전체 지역 장소추천 세부 화면으로 이동 (UI 동일)
- 장소 추천 세부 페이지 - RecommendDetail 
  - 장소추천 세부 UI (피그마 기반)
  - 해당 지역 장소 반환
  - 각 장소 클릭 시 상세페이지로 이동 (place 값 포함해서 전달)
  - 장소 추가 연결 -> DateSelected 페이지 구축 (contentid,  place 값 전달 )
  - 장소 검색 기능

+ 경기도 글씨 위치 수정 -> 따로 classname 부여 (사진 자체의 여백이 있는 것으로 보임 -> 따로 처리)

  
<table>
  <tr>
    <td>
      <video src="https://github.com/user-attachments/assets/331bc65a-4ef0-4588-9128-7ed76b55fca9" controls width="500"></video>
    </td>
    <td>
      <video src="https://github.com/user-attachments/assets/7fa5cdd1-1195-478a-86a5-2fb3ecca2536" controls width="500"></video>
    </td>
  </tr>
</table>

## 🚀 로직 설명 및 코드 설명

- API 관련
  - /recommend/postRecommendPlace.ts 작성

  - /calender/getAllPlace.ts 이용

<p>
<img width="231" alt="image" src="https://github.com/user-attachments/assets/e6388ec1-9454-4d54-afb5-4569171cb45a">
</p>

- 향후 dummydata 관련 부분 지우면서 dummy.png도 함께 삭제

## ⚠️ 마주쳤던 문제 및 해결 방법
없음

## ➕ 그 외에 추가적으로 구현된 사항
없음

## 🤔 테스트,검증 && 고민 사항
없음

### 📌 PR Comment 작성 시 Prefix for Reviewers

2024-09-14 11:08 UTC, jiheunkim requested changes
리뷰 완료했어여

2024-09-14 11:08 UTC, jiheunkim commented on frontend/src/pages/RecommendPage/styles/Recommend.style.tsx
https://github.com/user-attachments/assets/d7336448-17d4-49d0-9f18-e6a2f6b592ba

영상 보면 장소 추천 탭으로 넘어갈 때만 하단메뉴바 크기가 다른 거!! 수정필요!

2024-09-14 11:08 UTC, jiheunkim commented on frontend/src/pages/RecommendPage/styles/Recommend.style.tsx
<p>
 <img src="https://github.com/user-attachments/assets/c42afe0b-2821-4057-9be9-e66569760207" width="40%" />
</p>

- 아이폰 12 기준으로 잘 맞는건 확인했는데, 갤럭시 모델도 꽤 많이 쓸 거 같긴해서! 테스트 돌렸을 때 깨지면 안되니까 겉에 흰색 까는거랑 배경을 분리해서 따로 하는 게 좋을 거 같어~~

2024-09-14 11:08 UTC, jiheunkim commented on frontend/src/pages/RecommendPage/styles/Recommend.style.tsx
제주도도 위치 좀려서 제주 글씨가 흰색 안에 들어오게 해줌 좋을듯!!

2024-09-14 11:08 UTC, jiheunkim commented on frontend/src/pages/RecommendPage/styles/RecommendDetail.style.tsx
여기 하단바 피그마에 넣어두긴 했는데 제거해줄 수 있을까??

2024-09-14 11:08 UTC, jiheunkim commented on frontend/src/pages/RecommendPage/styles/RecommendDetail.style.tsx
그리고 경주 추천 장소 <- 여기서 경주랑 추천 장소 글씨 크기가 다른데 weight만 경주 지금처럼 강조해주고, 글씨 크기는 똑같이 해줬으면 좋겠어여!

2024-09-14 11:24 UTC, jiheunkim requested changes
추가 리뷰 보완!

2024-09-14 11:24 UTC, jiheunkim commented on frontend/src/pages/RecommendPage/RecommendDetail.tsx
``` tsx
<L.PlaceItem
    key={place.contentid}
    onClick={() => handleClick(place)}
  >
    <L.PlaceNumber>{index + 1}</L.PlaceNumber>
    <L.PlaceImage
      src={place.firstimage || dummyImage}
      alt={place.place}
    />
    <L.PlaceInfo>
      <L.PlaceName>{place.place}</L.PlaceName>
      <L.PlaceDescription>
        {`${locationName} · ${getContentTypeDescription(place.contenttypeid)}`}
      </L.PlaceDescription>
    </L.PlaceInfo>
    <L.AddButton
      onClick={e =>
        handleAddButtonClick(e, place.contentid, place.place)
      }
    >
      추가
    </L.AddButton>
</L.PlaceItem>
```
여기 부분 따로 컴포넌트로 분리해서 적용해주면 좋겠어!
ReccomendPage > components > PlaceItem.tsx 이런 식으로 만들어서 불러오는 방식으로!!!

2024-09-14 11:24 UTC, jiheunkim commented on frontend/src/pages/RecommendPage/RecommendDetail.tsx
BottomNav를 불러올 필요가 없음!
App.tsx 파일을 보면 여기서 하단메뉴바를 일괄적으로 적용시켜주고 있는데, 다른 리뷰메시지에 언급했듯이 그냥 하단바 여기서 안보여주는 쪽으로 합시당

2024-09-14 11:24 UTC, jiheunkim commented on frontend/src/pages/RecommendPage/RecommendDetail.tsx
여기 이미지 크기 좀 줄여서 아이폰 12 Pro 기준으로 하단바 뺐을 때 10개 목록 나타날 정도로 크기 좀 작게 조정해주면 좋겠웅 그 이후는 스크롤로 확인~

2024-09-14 11:39 UTC, jiheunkim commented on frontend/src/pages/RecommendPage/styles/RecommendDetail.style.tsx
각 장소 컴포넌트별로 bottomline 없애주면 좋겠구! PlaceItem 아래 언급했듯이 컴포넌트 분리하면 style 파일도 분리해서 만들어주면 좋을듯!
원하는 장소 검색 부분도 피그마랑 디자인 일치하게 통일해주라!

2024-09-14 16:11 UTC, katekim512 commented on frontend/src/pages/RecommendPage/styles/Recommend.style.tsx
✨해결

2024-09-14 16:12 UTC, katekim512 commented on frontend/src/pages/RecommendPage/RecommendDetail.tsx
✨ 해결

2024-09-14 16:14 UTC, katekim512 commented on frontend/src/pages/RecommendPage/styles/Recommend.style.tsx
✨ 해결

2024-09-14 16:32 UTC, katekim512 commented on frontend/src/pages/RecommendPage/RecommendDetail.tsx
> 여기 이미지 크기 좀 줄여서 아이폰 12 Pro 기준으로 하단바 뺐을 때 10개 목록 나타날 정도로 크기 좀 작게 조정해주면 좋겠웅 그 이후는 스크롤로 확인~

#### ✨ 해결
<img width="200" alt="image" src="https://github.com/user-attachments/assets/e9b3de91-5784-4616-aaf0-cf362b3bf523">

#### 💥 이슈
<img width="200" alt="image" src="https://github.com/user-attachments/assets/b28e6380-572b-4cef-bd1a-8f43f76d9a9b">

- 스크롤 하면 이렇게 처음 끊기는 곳에서 회색 그림자 선(?) 이 그어지는데 이유를 못 찾겠음

2024-09-14 17:00 UTC, katekim512 commented on frontend/src/pages/RecommendPage/RecommendDetail.tsx
> ```tsx
> <L.PlaceItem
>     key={place.contentid}
>     onClick={() => handleClick(place)}
>   >
>     <L.PlaceNumber>{index + 1}</L.PlaceNumber>
>     <L.PlaceImage
>       src={place.firstimage || dummyImage}
>       alt={place.place}
>     />
>     <L.PlaceInfo>
>       <L.PlaceName>{place.place}</L.PlaceName>
>       <L.PlaceDescription>
>         {`${locationName} · ${getContentTypeDescription(place.contenttypeid)}`}
>       </L.PlaceDescription>
>     </L.PlaceInfo>
>     <L.AddButton
>       onClick={e =>
>         handleAddButtonClick(e, place.contentid, place.place)
>       }
>     >
>       추가
>     </L.AddButton>
> </L.PlaceItem>
> ```
> 
> 여기 부분 따로 컴포넌트로 분리해서 적용해주면 좋겠어! ReccomendPage > components > PlaceItem.tsx 이런 식으로 만들어서 불러오는 방식으로!!!

✨ 해결

2024-09-14 17:04 UTC, katekim512 commented on frontend/src/pages/RecommendPage/styles/Recommend.style.tsx
> <img alt="" width="40%" src="https://private-user-images.githubusercontent.com/80433455/367510196-c42afe0b-2821-4057-9be9-e66569760207.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzMjkzMjcsIm5iZiI6MTcyNjMyOTAyNywicGF0aCI6Ii84MDQzMzQ1NS8zNjc1MTAxOTYtYzQyYWZlMGItMjgyMS00MDU3LTliZTktZTY2NTY5NzYwMjA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE0VDE1NTAyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2N2YxZWNhNDJmNTIzNTczNWMxMzVmMDBhMThjNTIyOTlmNGE0Mjc4OTMzNjg3NTU4Njg2MDgyZTJhMmYzMDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W9YuQuui7iWuKDVd-DNd1YbadOGGWDwimik9_-Z4lEA">
> 
> * 아이폰 12 기준으로 잘 맞는건 확인했는데, 갤럭시 모델도 꽤 많이 쓸 거 같긴해서! 테스트 돌렸을 때 깨지면 안되니까 겉에 흰색 까는거랑 배경을 분리해서 따로 하는 게 좋을 거 같어~~

✨ 해결

2024-09-14 18:12 UTC, jiheunkim commented on frontend/src/pages/RecommendPage/RecommendDetail.tsx
> > 여기 이미지 크기 좀 줄여서 아이폰 12 Pro 기준으로 하단바 뺐을 때 10개 목록 나타날 정도로 크기 좀 작게 조정해주면 좋겠웅 그 이후는 스크롤로 확인~
> 
> #### ✨ 해결
> <img alt="image" width="200" src="https://private-user-images.githubusercontent.com/127101670/367529305-e9b3de91-5784-4616-aaf0-cf362b3bf523.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzMzc2NDksIm5iZiI6MTcyNjMzNzM0OSwicGF0aCI6Ii8xMjcxMDE2NzAvMzY3NTI5MzA1LWU5YjNkZTkxLTU3ODQtNDYxNi1hYWYwLWNmMzYyYjNiZjUyMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxNFQxODA5MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOTljYzg0MjU3OWM5NmRiMGNkOTYwZmM4MjQ1ZDZmYWNiZDA1OTVkZTYwMGQyM2RlM2E4YjEyYzVlNWQxNjU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qw2PyHr3O9t9RV3D2KakC-h1lFOezSArF5W6QT55Jdc">
> #### 💥 이슈
> <img alt="image" width="200" src="https://private-user-images.githubusercontent.com/127101670/367529342-b28e6380-572b-4cef-bd1a-8f43f76d9a9b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzMzc2NDksIm5iZiI6MTcyNjMzNzM0OSwicGF0aCI6Ii8xMjcxMDE2NzAvMzY3NTI5MzQyLWIyOGU2MzgwLTU3MmItNGNlZi1iZDFhLThmNDNmNzZkOWE5Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxNFQxODA5MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMGYwZTJlYmU2NWQ0MDFkYzYzMjEyMWRiMTYwYjgwMmNhNDk0MWY2ZWNiZTk5MGY2ZjVkOWE3YWI0NTM3MmJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0IrlKp8nXo0NiIGqFDKZMB_bje6HW303XpUULzI4cQw">
> * 스크롤 하면 이렇게 처음 끊기는 곳에서 회색 그림자 선(?) 이 그어지는데 이유를 못 찾겠음

이슈 확인했어여 추후에 이 문제는 봅시당

2024-09-14 18:18 UTC, jiheunkim requested changes
이미지 대문자로 시작하는 거 한 번 체크해주고,
RecommendDetail.style.tsx에 남긴 리뷰 확인해주세욤

2024-09-14 18:18 UTC, jiheunkim commented on frontend/public/img/placeRecommend/Background.png
배포한거에서 이미지 이름이 대문자로 시작하면 지난번에 안뜨는 문제가 있었음! 이것도 그럴수도...!

2024-09-14 18:18 UTC, jiheunkim commented on frontend/src/pages/RecommendPage/styles/RecommendDetail.style.tsx
- 경주 추천 장소 <- 여기서 경주랑 추천 장소 글씨 크기가 다른데 weight만 경주 지금처럼 강조해주고, 글씨 크기는 똑같이 해주기!
- 여기 회색 선 지금보다 좀 더 길게해서 좌우여백 거의 없게 해줄 수 있나요?

![image](https://github.com/user-attachments/assets/01cac5ff-e491-4b8e-985d-9e535be27421)

2024-09-15 02:54 UTC, katekim512 commented on frontend/src/pages/RecommendPage/styles/RecommendDetail.style.tsx
> 여기 하단바 피그마에 넣어두긴 했는데 제거해줄 수 있을까??

✨ 해결

2024-09-15 02:56 UTC, katekim512 commented on frontend/src/pages/RecommendPage/styles/RecommendDetail.style.tsx
> 그리고 경주 추천 장소 <- 여기서 경주랑 추천 장소 글씨 크기가 다른데 weight만 경주 지금처럼 강조해주고, 글씨 크기는 똑같이 해줬으면 좋겠어여!

✨ 해결

2024-09-15 02:56 UTC, katekim512 commented on frontend/src/pages/RecommendPage/styles/RecommendDetail.style.tsx
> 각 장소 컴포넌트별로 bottomline 없애주면 좋겠구! PlaceItem 아래 언급했듯이 컴포넌트 분리하면 style 파일도 분리해서 만들어주면 좋을듯! 원하는 장소 검색 부분도 피그마랑 디자인 일치하게 통일해주라!

✨ 해결

2024-09-15 06:14 UTC, katekim512 commented on frontend/public/img/placeRecommend/Background.png
✨ 해결

2024-09-15 06:14 UTC, katekim512 commented on frontend/src/pages/RecommendPage/styles/RecommendDetail.style.tsx
✨ 해결

2024-09-15 06:16 UTC, jiheunkim approved these changes
확인완료!

2024-09-15 06:17 UTC, merged